name: CI/back-end

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./Back-end-API'] }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename:  ${{ matrix.dir }}/UnitTests/load_test.js

      - name: Test .net projects
        working-directory: ${{ matrix.dir }}
        run: | 
              dotnet build --configuration Release
              dotnet test --configuration Release
