name: ASP/CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./Back-end-API'] }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test .net projects
        working-directory: ${{ matrix.dir }}
        run: | 
              dotnet build --configuration Release
              dotnet test --configuration Release
              
      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: mattijs99/recipeapps3:latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
