name: CI/back-end

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./Back-end-API'] }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test .net projects
        working-directory: ${{ matrix.dir }}
        run: | 
              dotnet build --configuration Release
              dotnet test --configuration Release
