name: ASP/CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
  
      runs-on: ubuntu-latest
      
      steps:
      -uses: actions/checkout@v2
      -name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
      dotnet-version: 6.0
      -name: Build
      run: dotnet build --configuration Release
      -name: Run unitTests
      run: dotnet test --configuration Release
