name: VUE/CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./userinterface'] }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Vue unit tests
        working-directory: ${{ matrix.dir }}
        run: | 
              npm install
              npm run build
              npm run test:unit
        -name: Cypress e2e tests
         uses: cypress-io/github-action@v2

              

