name: VUE/CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./userinterface'] }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test vuejs projects
        working-directory: ${{ matrix.dir }}
        run: | 
              npm install
              npm run build
              npm run test:unit
              
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: |
            - args: [--filter myclient... --filter cypress-tests...]

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: pnpm --dir cypress/ cypress:ci
          start: pnpm --dir myclient/ dev
          wait-on: 'https://localhost:3000'
              

