name: VUE/CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./userinterface'] }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test vuejs projects
        working-directory: ${{ matrix.dir }}
        run: | 
              npm install
              npm run build
              npm run test:unit
              
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Back-end-API/Back-end-API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/recipeapp-userfrontend:latest
              

